### PR TITLE
Use OOP to ensure easy maintainability

### PR DESCRIPTION
**Pull request by zmontgo**
Separated CRUD, GET, and POST functions into modules that use classes to share variables. Ensures easy maintainability and easier to read.

### CODE REVIEW

**Comment by zmontgo** [comment]
Currently still in progress. Class methods called in an ugly and not future-proof way, hope to update it to call all class functions automatically. Maybe not all modules imported for the `/classes/` files.
Marked PR as draft.

**Comment by zmontgo** [comment]
This is still broken but I have been unable to test it for this entire day. I will test it when I am available again, but until then just have a bit of faith in my coding abilities haha.

**Comment by benjaminbhollon** [comment]
Hee hee, so I actually just did some of this already over on https://github.com/gamified-reading/gamified-reading and hadn't gotten around to porting it over here yet. Could you take a look at that code and see if it would solve your problem? If so, I'd prefer it since it's much more streamlined

**Comment by zmontgo** [comment]
Actually yes, that's very good. One thing, I'd want all the functions, as well as the GET and POST requests, to be in separate modules. Would that be possible?

**Comment by benjaminbhollon** [comment]
It might be, but the way you did it feels a bit messy. All the original code is still there, but I have to do an extra function call. I'm planning to look around for good ways to do that.

**Comment by benjaminbhollon** [comment]
Alright, I'm going to re-code this with the things we've learned now. I'll give you co-author credit in the commits

**Pull request closed without merging**
