### PR TITLE
ESLint fixes, stylistic fixes

### LINKED ISSUE #4: Use ESLint
Use ESLint to enforce syntax style and catch errors. Will be a helpful part of the review process before pulling into the main branch. Use GitHub Actions to automate this and prevent people from pulling until the linter errors are fixed. Also require at least one review, in case you ever have more than just you and I working on this project, it can be helpful to ensure that someone has manually gone through and looked at the code to make sure it all works well.
Just putting this as an issue because I have no idea how to set it up myself.

### LINKED ISSUE #8: Extrapolate email text into import from file
Put the email subject, body, etc. into an object and use those to keep `app.js` clean.

### PR DESCRIPTION
**Pull request by zmontgo**
Began cleaning up code. Extrapolated long strings into json files in `/bin`. Flattened buttons to keep consistent with the rest of the theme.

### CODE REVIEW

**Comment by zmontgo** [comment]
Transitioned to use PM2 instead of simply running the app using `node app.js`. PM2 is made to run applications all the time, logging errors, warnings, and normal logs in different files, letting you exit the terminal while keeping the app running, and ensuring that the app stays running fast for long periods of time. Useful for both development and production environments!

**Comment by zmontgo** [comment]
Run `npm start` to start the application, and `npm stop` to stop it. It will remain running if you don't. Remember to re-run `npm install` to get the PM2 package.

**Comment by benjaminbhollon** [comment]
The crud functions weren't returning anything, so I fixed that.

**Review by benjaminbhollon — CHANGES_REQUESTED** [review]
Great job! I'm willing to merge if you can let me know how you ran the eslint checker.

**Review by benjaminbhollon — APPROVED** [review]

**Comment by benjaminbhollon** [comment]
I added `npm test` to run ESLint and try to automatically fix errors.

**Pull request merged**
